### ISSUE TITLE
issue title

### ISSUE THREAD

**Issue by junminahn** [junminahn/testteste#2]
```yml
realmName: ospp2ffffgggf
clientName: test-client
environments:
    - dev:
        redirectUrls:
            - https://example.com
            - https://example.com2
    - test:
        redirectUrls:
            - https://testexample.com
            - https://testexample.com2
```
