### ISSUE TITLE
issue template 2

### ISSUE THREAD

**Issue by junminahn** [junminahn/testteste#3]
```yml
realmName: ospp2ffffgaaavbbaa
clientName: test-client
environments:
    - dev:
        redirectUrls:
            - https://example.com
            - https://example.com2
    - test:
        redirectUrls:
            - https://testexample.com
            - https://testexample.com2
```
